### ISSUE TITLE
Unable to utilize json_query

### ISSUE THREAD

**Issue by rothman857** [ansible/default-test-container#82]
I believe this container is missing the `jmespath` library, which is a requirement for using the `json_query` Ansible filter.

The following task:
```
- name: Test json_query
      ansible.builtin.debug:
      msg: "{{ '' | community.general.json_query('*') }}"
```

Results in the following error:
```
fatal: [testhost]: FAILED! => {"msg": "You need to install \"jmespath\" prior to running json_query filter"}
```

Link to jmespath:
https://pypi.org/project/jmespath/

**Comment by mattclay** [comment]
This container only includes requirements for plugins in ansible-core.

Any requirements for plugins in collections should be handled in those collections. For example, the `community.general` collection could specify `jmespath` in the `tests/integration/requirements.txt` file to make it available to integration tests.
